[package]
name = "rock-paper-scissors"
version = "0.1.0"

[dependencies]
lazy_static = "1.0"
rand = "0.5"
rocket = "0.3.16"
rocket_codegen = "0.3.16"
sha2 = "0.7"

[dependencies.rocket_contrib]
version = "0.3.16"
default-features = false
features = ["handlebars_templates"]
